import logging

from fastapi import HTTPException
from langchain_google_genai import ChatGoogleGenerativeAI

from app.config import settings

logger = logging.getLogger("uvicorn.error")

api_key = settings.GEMINI_API_KEY
model_name = settings.GEMINI_MODEL

if not api_key:
    logger.critical(
        "❌ ERROR: GEMINI_API_KEY is missing or empty inside settings config."
    )
    raise ValueError(
        "GEMINI_API_KEY is not configured properly."
    )

logger.info(
    f"🤖 Initializing LangChain Gemini LLM with model: {model_name}"
)

llm = ChatGoogleGenerativeAI(
    model=settings.GEMINI_MODEL,
    google_api_key=settings.GEMINI_API_KEY,
    temperature=settings.GEMINI_TEMPERATURE,
)


def extract_text_response(response) -> str:
    """
    Extract plain text from a LangChain AIMessage response.
    """

    content = response.content

    if isinstance(content, str):
        return content

    if isinstance(content, list):
        text_parts = []

        for item in content:
            if (
                isinstance(item, dict)
                and item.get("type") == "text"
            ):
                text_parts.append(
                    item.get("text", "")
                )

        return "\n".join(text_parts)

    return ""


def generate_response(
    prompt: str,
) -> str:
    """
    Generate an AI response from a fully formatted prompt.
    """

    try:
        response = llm.invoke(prompt)

        answer = extract_text_response(response)

        if not answer:
            logger.warning(
                "⚠️ Gemini returned an empty response."
            )

            return (
                "No content could be generated by the model."
            )

        return answer

    except Exception as e:
        logger.exception("Gemini API Error")

        error_message = str(e)

        if "503" in error_message:
            raise HTTPException(
                status_code=503,
                detail=(
                    "Gemini service is currently busy. "
                    "Please try again in a few moments."
                ),
            )

        if "429" in error_message:
            raise HTTPException(
                status_code=429,
                detail=(
                    "Gemini API quota exceeded. "
                    "Please try again later."
                ),
            )

        if "404" in error_message:
            raise HTTPException(
                status_code=404,
                detail="Configured Gemini model was not found.",
            )

        raise HTTPException(
            status_code=500,
            detail=(
                "An unexpected error occurred while "
                "generating the AI response."
            ),
        )