import { zodResolver } from '@hookform/resolvers/zod'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate } from 'react-router-dom'
import { z } from 'zod'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input, PasswordInput } from '@/components/ui/input'
import { getApiErrorMessage } from '@/features/auth/api'
import { useAuth } from '@/hooks/useAuth'
import { useToast } from '@/hooks/useToast'
const schema = z.object({ name: z.string().trim().min(3, 'Name must have at least 3 characters.'), email: z.string().trim().email('Enter a valid email address.'), password: z.string().min(6, 'Password must have at least 6 characters.') }); type Values = z.infer<typeof schema>
export function RegisterPage() { const { register: createAccount } = useAuth(); const { showToast } = useToast(); const navigate = useNavigate(); const [error, setError] = useState<string | null>(null); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema) }); const submit = async (values: Values) => { setError(null); try { await createAccount(values.name, { email: values.email, password: values.password }); showToast({ title: 'Account created', description: 'You can now sign in with your new account.', variant: 'success' }); navigate('/login', { replace: true }) } catch (err) { setError(getApiErrorMessage(err)) } }; return <main className="grid min-h-screen place-items-center bg-muted/40 p-6"><Card className="w-full max-w-md"><CardHeader><CardTitle>Create account</CardTitle><CardDescription>Create an account to access your workspace.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={handleSubmit(submit)} noValidate>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div><label htmlFor="name" className="text-sm font-medium">Name</label><Input id="name" className="mt-1" autoComplete="name" {...register('name')} />{errors.name && <p className="mt-1 text-sm text-destructive">{errors.name.message}</p>}</div><div><label htmlFor="email" className="text-sm font-medium">Email</label><Input id="email" className="mt-1" type="email" autoComplete="email" {...register('email')} />{errors.email && <p className="mt-1 text-sm text-destructive">{errors.email.message}</p>}</div><div><label htmlFor="password" className="text-sm font-medium">Password</label><PasswordInput id="password" className="mt-1" autoComplete="new-password" {...register('password')} />{errors.password && <p className="mt-1 text-sm text-destructive">{errors.password.message}</p>}</div><Button className="w-full" type="submit" loading={isSubmitting}>Create account</Button></form><p className="mt-4 text-sm text-muted-foreground">Already have an account? <Link className="underline" to="/login">Sign in</Link></p></CardContent></Card></main> }
