import { useState, type FormEvent } from 'react'
import { PageHeader } from '@/components/app/PageHeader'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { EmptyState, ErrorState, Skeleton } from '@/components/ui/feedback'
import { Input } from '@/components/ui/input'
import { apiError, searchKnowledge } from '@/features/api/client'
import type { SearchResponse, SearchResult } from '@/features/api/types'
const source = (result: SearchResult) => { const name = result.metadata?.filename ?? result.metadata?.source; return result.filename ?? result.document ?? (typeof name === 'string' ? name : 'Unknown document') }; const content = (result: SearchResult) => result.content ?? (typeof result.metadata?.content === 'string' ? result.metadata.content : 'No text snippet returned by the API.'); const score = (result: SearchResult) => { const value = result.similarity ?? result.score ?? result.distance; return typeof value === 'number' ? value.toFixed(3) : 'Not supplied' }; function Highlight({ text, query }: { text: string; query: string }) { const parts = text.split(new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'ig')); return <>{parts.map((part, index) => part.toLowerCase() === query.toLowerCase() ? <mark key={index} className="rounded bg-warning/25 px-0.5 text-inherit">{part}</mark> : part)}</> }
export function SearchPage() { const [question, setQuestion] = useState(''); const [submitted, setSubmitted] = useState(''); const [response, setResponse] = useState<SearchResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const run = async (query: string) => { setLoading(true); setError(null); setSubmitted(query); try { setResponse(await searchKnowledge(query)) } catch (err) { setError(apiError(err, 'Search failed.')); setResponse(null) } finally { setLoading(false) } }; const submit = (event: FormEvent) => { event.preventDefault(); const query = question.trim(); if (query) void run(query) }; const results = Array.isArray(response?.results) ? response.results : []; return <div className="mx-auto max-w-4xl"><PageHeader title="Semantic search" description="Search indexed knowledge with the backend retrieval service." /><form className="flex flex-col gap-2 sm:flex-row" onSubmit={submit}><Input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Search your knowledge base" aria-label="Search question" /><Button loading={loading} disabled={!question.trim()}>Search</Button></form><section className="mt-6 space-y-3" aria-live="polite">{loading && [1, 2, 3].map((item) => <Skeleton key={item} className="h-28" />)}{error && <ErrorState title="Search unavailable" description={error} action={<Button onClick={() => void run(submitted)}>Try again</Button>} />}{!loading && !error && response && results.length === 0 && <EmptyState title={response.displayable ? 'No matching documents found.' : 'Search completed successfully but no displayable results were returned.'} description="Try another question or upload more knowledge." className="py-14" />}{!loading && results.map((result, index) => <Card key={`${source(result)}-${index}`}><CardContent className="p-5"><div className="flex flex-col justify-between gap-1 sm:flex-row sm:gap-4"><h2 className="font-medium">{source(result)}</h2><span className="shrink-0 text-xs text-muted-foreground">Similarity: {score(result)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground"><Highlight text={content(result)} query={submitted} /></p></CardContent></Card>)}{response === null && !loading && !error && <EmptyState title="Ask your first search question" description="Results from your indexed documents will appear here." className="py-14" />}</section></div> }
