import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Switch } from '@/components/ui/form-controls'
import { Notice } from '@/components/app/Notice'
import { PageHeader } from '@/components/app/PageHeader'
import { apiError, getHealth, getVersion } from '@/features/api/client'
import { useTheme } from '@/hooks/useTheme'
type Status = { health: string; version: string } | null
export function SettingsPage() { const { theme, setTheme } = useTheme(); const [status, setStatus] = useState<Status>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const check = async () => { setLoading(true); setError(null); try { const [health, version] = await Promise.all([getHealth(), getVersion()]); setStatus({ health: health.status, version: version.version }) } catch (err) { setError(apiError(err, 'Backend status check failed.')) } finally { setLoading(false) } }; useEffect(() => { void check() }, []); return <div className="mx-auto max-w-2xl"><PageHeader title="Settings" description="Appearance and backend connectivity." /><div className="space-y-4"><Card><CardContent className="flex items-center justify-between p-6"><div><h2 className="font-medium">Dark theme</h2><p className="text-sm text-muted-foreground">Use the dark color scheme.</p></div><Switch checked={theme === 'dark'} onChange={(event) => setTheme(event.target.checked ? 'dark' : 'light')} aria-label="Toggle dark theme" /></CardContent></Card><Card><CardContent className="space-y-3 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-medium">Backend status</h2><p className="text-sm text-muted-foreground">Live checks against the FastAPI service.</p></div><Button variant="outline" onClick={() => void check()} loading={loading}>Check API</Button></div>{error && <Notice>{error}</Notice>}{status && <dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Health</dt><dd className="font-medium">{status.health}</dd></div><div><dt className="text-muted-foreground">Version</dt><dd className="font-medium">{status.version}</dd></div></dl>}</CardContent></Card></div></div> }
