import { FileText, Upload } from 'lucide-react'
import { useRef, useState, type ChangeEvent, type DragEvent } from 'react'
import { PageHeader } from '@/components/app/PageHeader'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Progress } from '@/components/ui/feedback'
import { apiError, uploadPdf } from '@/features/api/client'
import { useToast } from '@/hooks/useToast'

export function UploadPage() {
  const [file, setFile] = useState<File | null>(null); const [progress, setProgress] = useState(0); const [dragging, setDragging] = useState(false); const [loading, setLoading] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null); const { showToast } = useToast()
  const select = (next: File | undefined) => { if (!next) return; if (next.type !== 'application/pdf' && !next.name.toLowerCase().endsWith('.pdf')) { showToast({ title: 'Unsupported file', description: 'Only PDF files can be uploaded.', variant: 'destructive' }); return } setFile(next); setProgress(0) }
  const choose = (event: ChangeEvent<HTMLInputElement>) => select(event.target.files?.[0])
  const drop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); setDragging(false); select(event.dataTransfer.files[0]) }
  const submit = async () => { if (!file) { showToast({ title: 'Choose a PDF first', variant: 'destructive' }); return }; setLoading(true); setProgress(0); try { const response = await uploadPdf(file, setProgress); window.dispatchEvent(new Event('documents:changed')); showToast({ title: 'Upload complete', description: `${response.filename} is queued for ingestion.`, variant: 'success' }); setFile(null) } catch (err) { showToast({ title: 'Upload failed', description: apiError(err, 'The document could not be uploaded.'), variant: 'destructive' }) } finally { setLoading(false) } }
  return <div className="mx-auto max-w-2xl"><PageHeader title="Upload PDF" description="Add a PDF to the knowledge base. It will be processed in the background." /><Card><CardHeader><CardTitle>Document upload</CardTitle><CardDescription>PDF files only. Your document is securely sent to the ingestion queue.</CardDescription></CardHeader><CardContent className="space-y-5"><div role="button" tabIndex={0} onClick={() => inputRef.current?.click()} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') inputRef.current?.click() }} onDragOver={(event) => { event.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={drop} className={`focus-ring cursor-pointer rounded-xl border-2 border-dashed p-10 text-center transition-colors ${dragging ? 'border-primary bg-primary/5' : 'border-border hover:bg-muted/50'}`}><Upload className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 font-medium">Drag and drop a PDF here</p><p className="mt-1 text-sm text-muted-foreground">or click to browse your files</p><input ref={inputRef} className="sr-only" type="file" accept="application/pdf,.pdf" onChange={choose} disabled={loading} /></div>{file && <div className="flex items-center gap-3 rounded-lg bg-muted/60 p-3"><FileText className="size-5 text-muted-foreground" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{file.name}</p><p className="text-xs text-muted-foreground">{(file.size / 1024 / 1024).toFixed(2)} MB</p></div><Button size="sm" variant="ghost" onClick={() => setFile(null)} disabled={loading}>Remove</Button></div>}{loading && <div className="space-y-2"><div className="flex justify-between text-sm"><span>Uploading document</span><span>{progress}%</span></div><Progress value={progress} label="Upload progress" /></div>}<Button className="w-full sm:w-auto" onClick={() => void submit()} loading={loading} disabled={!file}><Upload className="size-4" />Upload PDF</Button></CardContent></Card></div>
}
